### ISSUE TITLE
sqllite lock error

### ISSUE THREAD

**Issue by TheWylot** [AlessioGr/NotQuests#171]
this error actually caused in 1.19.2 purpur

[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/INFO]: [NotQuests]: There was an error saving the PlayerData of player with UUID  PRIVATE  Stacktrace:
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at org.sqlite.core.DB.execute(DB.java:881)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:922)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at notquests-5.8.4.jar//rocks.gravili.notquests.paper.shadow.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at notquests-5.8.4.jar//rocks.gravili.notquests.paper.shadow.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at notquests-5.8.4.jar//rocks.gravili.notquests.paper.managers.QuestPlayerManager.savePlayerDataInternal(QuestPlayerManager.java:712)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at notquests-5.8.4.jar//rocks.gravili.notquests.paper.managers.QuestPlayerManager.saveSinglePlayerData(QuestPlayerManager.java:90)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at notquests-5.8.4.jar//rocks.gravili.notquests.paper.events.QuestEvents.lambda$onDisconnectEvent$21(QuestEvents.java:1301)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:02:08] [Craft Scheduler Thread - 4771 - NotQuests/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by AlessioGr** [comment]
> org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)

Is there a chance you've used reload plugins like plugman or serverutils, or otherwise reloaded the server with /reload?

Because that usually causes this error

**Comment by TheWylot** [comment]
there isn't any chance cause i didnt use plugman

**Comment by AlessioGr** [comment]
(Hopefully) fixed in recent versions
