### ISSUE TITLE
NQA Editor throws PKIX Exception

### ISSUE THREAD

**Issue by kekropp** [AlessioGr/NotQuests#192]
How to reproduce:

**NotQuests version:** 5.13.1
**NotQuests module:** Paper
**Server version:** git-Paper-413 (MC: 1.19.3)
**Server Brand:** Paper
**Java version:** 17.0.6
**Enabled integrations:**
> - Vault *(1.7.3-b131)*
> - WorldEdit *(7.2.13+46576cc)*
> - Citizens *(2.0.30-SNAPSHOT (build 2888))*
> - LuckPerms *(5.4.40)*
> - Towny *(0.98.6.0)*

**Run**: `/nqa editor`

```
mc-minecraft-1  | [11:48:53 WARN]: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.managers.WebManager.sendRequest(WebManager.java:68)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.managers.WebManager.openEditor(WebManager.java:79)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.commands.AdminCommands.lambda$new$29(AdminCommands.java:699)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandManager.executeCommand(CommandManager.java:189)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
mc-minecraft-1  | [11:48:53 WARN]:      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
mc-minecraft-1  | [11:48:53 WARN]:      at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912)
mc-minecraft-1  | [11:48:53 WARN]:      at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
mc-minecraft-1  | [11:48:53 WARN]:      at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:316)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:300)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.TickTask.run(TickTask.java:18)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/java.lang.Thread.run(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.validator.PKIXValidator.doValidate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.validator.Validator.validate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      ... 55 more
mc-minecraft-1  | [11:48:53 WARN]: Caused by: java.security.cert.CertPathValidatorException: validity check failed
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/java.security.cert.CertPathValidator.validate(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      ... 60 more
mc-minecraft-1  | [11:48:53 WARN]: Caused by: java.security.cert.CertificateExpiredException: NotAfter: Fri Jan 20 04:24:22 UTC 2023
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.x509.CertificateValidity.valid(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/sun.security.provider.certpath.BasicChecker.check(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      ... 65 more
mc-minecraft-1  | [11:48:53 WARN]: Unexpected character (C) at position 0.
mc-minecraft-1  | [11:48:53 WARN]:      at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
mc-minecraft-1  | [11:48:53 WARN]:      at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
mc-minecraft-1  | [11:48:53 WARN]:      at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
mc-minecraft-1  | [11:48:53 WARN]:      at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
mc-minecraft-1  | [11:48:53 WARN]:      at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.commands.AdminCommands.lambda$new$29(AdminCommands.java:709)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandManager.executeCommand(CommandManager.java:189)
mc-minecraft-1  | [11:48:53 WARN]:      at notquests-5.13.1.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
mc-minecraft-1  | [11:48:53 WARN]:      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
mc-minecraft-1  | [11:48:53 WARN]:      at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912)
mc-minecraft-1  | [11:48:53 WARN]:      at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
mc-minecraft-1  | [11:48:53 WARN]:      at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:316)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:300)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.TickTask.run(TickTask.java:18)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
mc-minecraft-1  | [11:48:53 WARN]:      at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
mc-minecraft-1  | [11:48:53 WARN]:      at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by AlessioGr** [comment]
Fixed in recent versions
