### ISSUE TITLE
Class Def Not Found with beton quests integration

### ISSUE THREAD

**Issue by PaintsplattersMC** [AlessioGr/NotQuests#212]
I get the following error in console when i try to load up Beton Quests intergation

running paper 538 119.4

NotQuests 5.17.1

BetonQuests 2.12.11-dev (also had this issue with latest stable)

This is kind of important as beton quest has lots of support that i need for things like mmoitems, mmocore and denizen

```[03:33:42] [Server thread/INFO]: [NotQuests]: MythicMobs found. Enabled MythicMobs support!
[03:33:42] [Server thread/ERROR]: Error occurred while enabling NotQuests v5.17.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/betonquest/betonquest/BetonQuest
	at rocks.gravili.notquests.paper.managers.integrations.betonquest.BetonQuestManager.<init>(BetonQuestManager.java:39) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.paper.managers.integrations.IntegrationsManager.lambda$new$20(IntegrationsManager.java:211) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.paper.managers.integrations.Integration.enable(Integration.java:135) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.paper.managers.integrations.Integration.enable(Integration.java:123) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.paper.managers.integrations.IntegrationsManager.enableIntegrations(IntegrationsManager.java:442) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.paper.NotQuests.onEnable(NotQuests.java:170) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.Main.onEnable(Main.java:71) ~[notquests-5.17.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.betonquest.betonquest.BetonQuest
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
[03:33:42] [Server thread/INFO]: [NotQuests] Disabling NotQuests v5.17.1
[03:33:42] [Server thread/INFO]: [NotQuests]: NotQuests is shutting down...
[03:33:42] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling NotQuests v5.17.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "rocks.gravili.notquests.paper.managers.QuestPlayerManager.getActiveQuestPlayers()" because the return value of "rocks.gravili.notquests.paper.NotQuests.getQuestPlayerManager()" is null
	at rocks.gravili.notquests.paper.managers.DataManager.saveData(DataManager.java:1504) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.paper.NotQuests.onDisable(NotQuests.java:391) ~[notquests-5.17.1.jar:?]
	at rocks.gravili.notquests.Main.onDisable(Main.java:114) ~[notquests-5.17.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by AlessioGr** [comment]
Betonquest v1 is not supported. Only Betonquest v2 is supported

**Comment by PaintsplattersMC** [comment]
i meant 2.11 i made a typo

**Comment by PaintsplattersMC** [comment]
bump
