### ISSUE TITLE
`/nqa completedQuests` crashes server

### ISSUE THREAD

**Issue by MaksyKun** [AlessioGr/NotQuests#220]
When starting to type in `/nqa completedQuests [...]` the server crashes instantly.

The following error occurs:
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3
// 
// DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!
// 

Time: 2024-12-20 13:12:18
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Could not initialize class rocks.gravili.notquests.paper.shadow.cloud.bukkit.internal.MinecraftArgumentTypes
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.parsers.selector.SelectorUtils.createEntityArgument(SelectorUtils.java:90)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.parsers.selector.SelectorUtils.lambda$createModernParser$0(SelectorUtils.java:80)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.brigadier.argument.WrappedBrigadierParser.suggestions(WrappedBrigadierParser.java:195)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.parsers.selector.SelectorUtils$ModernSelectorParser.suggestions(SelectorUtils.java:323)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.parsers.selector.SelectorUtils$SelectorParser.suggestions(SelectorUtils.java:202)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.parsers.selector.SinglePlayerSelectorArgument$SinglePlayerSelectorParser.suggestions(SinglePlayerSelectorArgument.java:161)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.arguments.DelegatingSuggestionsProvider.apply(DelegatingSuggestionsProvider.java:47)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.arguments.DelegatingSuggestionsProvider.apply(DelegatingSuggestionsProvider.java:33)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandTree.directSuggestions(CommandTree.java:715)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandTree.suggestionsForDynamicArgument(CommandTree.java:630)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandTree.getSuggestions(CommandTree.java:570)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandTree.getSuggestions(CommandTree.java:532)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandTree.getSuggestions(CommandTree.java:532)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandTree.getSuggestions(CommandTree.java:493)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.arguments.DelegatingCommandSuggestionEngine.getSuggestions(DelegatingCommandSuggestionEngine.java:77)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.CommandManager.suggest(CommandManager.java:219)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.BukkitCommand.tabComplete(BukkitCommand.java:98)
	at org.bukkit.command.Command.tabComplete(Command.java:101)
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigSuggestionProvider.getSuggestions(BukkitCommandNode.java:118)
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71)
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551)
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:893)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$2(ServerGamePacketListenerImpl.java:854)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:83)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:76)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:72)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.shadow.cloud.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:137)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.managers.CommandManager.preSetupGeneralCommands(CommandManager.java:385)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.managers.CommandManager.preSetupCommands(CommandManager.java:371)
	at notquests-5.19.0.jar//rocks.gravili.notquests.paper.NotQuests.onEnable(NotQuests.java:206)
	at notquests-5.19.0.jar//rocks.gravili.notquests.Main.onEnable(Main.java:71)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
	... 2 more

```

**Comment by TabZz147** [comment]
Is there a fix for this?

**Comment by MaksyKun** [comment]
There is a initial build that comes up with a refactoring to solve this issue. But it is still unstable and gets some work from time to time when my RL gets less stressed

**Comment by TabZz147** [comment]
Ok i will wait ty
